### ISSUE TITLE
Line shape function

### ISSUE THREAD

**Issue by gharib85** [spalato/Mbo.jl#1]
I feel frustrated 
Same implementation found in pyrho 
https://github.com/berkelbach-group/pyrho/blob/master/spec/spectroscopy.py

While other package using correlation of dipole operator 
I wonder if they return same answer
https://github.com/whaley-group-berkeley/QSpectra/blob/master/qspectra/simulate/response.py

**Comment by spalato** [comment]
Hi gharib,

The code in `Mbo.jl` implements the modeling of spectroscopic response using the cumulant expansion truncated to second order. This is an approximation of the correlation function of the dipole moment. In principle, both methods should yield the same results, provided the approximations are valid. 

I pieced it together using the following textbooks: 
- Chapters 7 and 8 in Mukamel, S. Principles of nonlinear optical spectroscopy. (Oxford University Press, 1995). 
- Cho, M. Two-dimensional optical spectroscopy. (CRC Press, 2009). (I don't have it on hand, maybe chapter 3?)
I think the textbook by Mukamel makes every approximation explicit, if you read carefully...

Thanks for the links. I didn't know these packages.

May I ask what is causing frustration?

**Comment by gharib85** [comment]
@spalato 
Thanks for reply 
I found to different implementation for optical absorption
First ....
https://github.com/whaley-group-berkeley/QSpectra/blob/master/qspectra/simulate/response.py
Which using Fourier transform of dipole correlation 
Second ....
https://github.com/berkelbach-group/pyrho/blob/master/spec/spectroscopy.py
Which using line function

**Comment by gharib85** [comment]
@spalato thanks for your reply
I am going to read this chapter
